GET https://integration-api-6cas.onrender.com/auth/login/success
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Cookie: connect.sid=s%3A1AdIg8UFMT8RnItUBBpkYFRrb71ltCE5.KydNuBbu2NiQFZjInAZvAgbQUZW%2B8wiZALTW%2FWvxHlo
Origin: http://localhost:5173
Referer: http://localhost:5173/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
sec-ch-ua: "Brave";v="117", "Not;A=Brand";v="8", "Chromium";v="117"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

###
GET http://localhost:3001/auth/login/success
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Cookie: connect.sid=s%3A1AdIg8UFMT8RnItUBBpkYFRrb71ltCE5.KydNuBbu2NiQFZjInAZvAgbQUZW%2B8wiZALTW%2FWvxHlo
Host: localhost:3001
Origin: http://localhost:5173
Referer: http://localhost:5173/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
sec-ch-ua: "Brave";v="117", "Not;A=Brand";v="8", "Chromium";v="117"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

###
GET /auth/login/success HTTP/1.1
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Cookie: connect.sid=s%3AVtdU-hV9Gy0O1Z7S25zhI_w6ds1Ec1HD.imSibpDmxwfOU%2FJDO17SrTkB5uES%2FVKZl2uB5TsAhw8
Host: localhost:3001
Origin: http://localhost:5173
Referer: http://localhost:5173/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
sec-ch-ua: "Brave";v="117", "Not;A=Brand";v="8", "Chromium";v="117"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

###
GET http://localhost:3001/api/anecdotes/

###
GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/anecdotes/
content-type: application/json

{
    "content": "If it hurts, do it more often",
    "author": "Jez Humble",
    "info": "https://martinfowler.com/bliki/FrequencyReducesDifficulty.html",
    "votes": 21
}

###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "userName": "saw",
    "name": "Superuser",
    "password": "saw",
    "email": "saw@gmail.com",
    "source": "local"
}

###
POST http://localhost:3001/api/anecdotes/
content-type: application/json

{
    "content": "Pr",
    "author": "Donald Knuth",
    "info": "http://wiki.c2.com/?PrematureOptimization",
    "votes": 1
}

###
POST http://localhost:3001/api/anecdotes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MWQ0Y2ViZjNhZDU0MTMwYTE1MzU4YiIsImlhdCI6MTY5NjQ3OTI0OCwiZXhwIjoxNjk2NDgyODQ4fQ.7r50zQFjpBv1kkvLNE3iMToKrrJoSsohSLTmmSoQ5Hc

{
    "content": "Premature optimization is the root of all evil",
    "author": "Donald Knuth",
    "info": "http://wiki.c2.com/?PrematureOptimization",
    "votes": 1
}
###
POST http://localhost:3001/api/login-local/success
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MWQ0Y2ViZjNhZDU0MTMwYTE1MzU4YiIsImlhdCI6MTY5NjQ3OTI0OCwiZXhwIjoxNjk2NDgyODQ4fQ.7r50zQFjpBv1kkvLNE3iMToKrrJoSsohSLTmmSoQ5Hc


###
GET http://localhost:3001/api/verify-email/?token=$2b$10$bGdf1GZ6JfSZrFyRVceWueHYE7qHYAfjsGezPkQuU/I.OFEBdNbf6

###
POST http://localhost:3001/api/login-local/
content-type: application/json

{
    "email": "renelynwillhelpyou@gmail.com",
    "password": "21"
}

# ###
# GET http://localhost:3001/info/

# ###
# GET  http://localhost:3001/api/persons/1

# ###
# GET  http://localhost:3001/api/persons/64d63c45e3583a8cc2dd1ba8

# ###
# DELETE http://localhost:3001/api/persons/64d63c1eb5a442d2a637326f

# ###
# PUT http://localhost:3001/api/persons/64d63c45e3583a8cc2dd1ba8
# content-type: application/json

# {
#     "name":"Arto Hellas",
#     "number": 218
# }